# Generated by Django 5.2.1 on 2025-05-26 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="trips.trip",
            ),
        ),
    ]
