# Generated by Django 5.2.1 on 2025-06-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="country",
            field=models.CharField(default="Canada", max_length=100),
            preserve_default=False,
        ),
    ]
