# Generated by Django 5.2.1 on 2025-06-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_location_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="visited_on",
            field=models.DateField(default="2025-01-01"),
            preserve_default=False,
        ),
    ]
